# Generated by Django 4.1.5 on 2023-02-02 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interface', '0002_like_delete_login_delete_signup_delete_xogin'),
    ]

    operations = [
        migrations.CreateModel(
            name='AddUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=64)),
                ('second_name', models.CharField(max_length=64)),
                ('pass_word', models.CharField(max_length=64)),
                ('pass_word2', models.CharField(max_length=64)),
                ('user_name', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='login',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=64)),
                ('pass_word', models.CharField(max_length=64)),
            ],
        ),
    ]
