# Generated by Django 4.1.5 on 2023-02-03 14:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('interface', '0003_adduser_login'),
    ]

    operations = [
        migrations.RenameField(
            model_name='adduser',
            old_name='pass_word2',
            new_name='last_name',
        ),
        migrations.RemoveField(
            model_name='adduser',
            name='second_name',
        ),
    ]
