# Generated by Django 4.1.5 on 2023-02-06 14:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('interface', '0004_rename_pass_word2_adduser_last_name_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='adduser',
            table='AddUser',
        ),
    ]
