# Generated by Django 4.1.5 on 2023-02-06 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interface', '0005_alter_adduser_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='adduser',
            name='Email',
            field=models.EmailField(blank=True, max_length=64, null=True),
        ),
    ]
