# Generated by Django 4.1.5 on 2023-02-07 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interface', '0006_adduser_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('user_name', models.CharField(max_length=64)),
                ('pass_word', models.CharField(max_length=64)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.DeleteModel(
            name='login',
        ),
        migrations.AlterModelTable(
            name='adduser',
            table='adduser',
        ),
    ]
