# Generated by Django 4.1.5 on 2023-02-07 14:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('interface', '0007_user_delete_login_alter_adduser_table'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='last_login',
        ),
        migrations.RemoveField(
            model_name='user',
            name='password',
        ),
    ]
